# Generated by Django 4.2.30 on 2026-06-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='supervisor_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
